[package]
name = "cmf"
version = "0.1.0"
edition = "2021"
authors = ["yanosea"]
description = "cargo-make × fzf"
license = "MIT"
repository = "https://github.com/yanosea/cmf"
exclude = ["/.git", ".gitignore"]

[dependencies]
colored = "2.0"
crossterm = "0.19.0"
indicatif = "0.15.0"
toml = "0.5"
