pub const ARG_QUERY: &str = "--query";
pub const COMMAND_FZF: &str = "fzf";
pub const ERROR_FAILED_TO_CONVERT_OUTPUT: &str = "Failed to convert output to UTF-8";
pub const ERROR_FAILED_TO_OPEN_STDIN: &str = "Failed to open stdin";
pub const ERROR_FAILED_TO_PARSE_TOML: &str = "Failed to parse TOML";
pub const ERROR_FAILED_TO_READ_TASKS: &str = "Failed to read tasks from TOML";
pub const ERROR_FAILED_TO_SPAWN_FZF: &str = "Failed to spawn fzf";
pub const KEY_TASKS: &str = "tasks";
pub const PATH_MAKEFILE: &str = "Makefile.toml";
